# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20171125_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='particle',
        ),
        migrations.AddField(
            model_name='experiment',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Document'),
        ),
    ]
