# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_auto_20180322_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='ambipolar_diff_coefficient',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='diff_coefficient',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='let_values_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='particles_count',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='trials_count',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
