# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 17:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0012_auto_20180407_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=2)),
                ('supply_voltage', models.FloatField()),
                ('resistance', models.FloatField(default=15000.0)),
                ('capacitance', models.FloatField(default=1e-15)),
                ('model_type', models.CharField(choices=[('point', 'Точечная модель'), ('voltage', 'Модель напряжений')], max_length=50)),
                ('sim_type', models.CharField(choices=[('monte_carlo', 'Монте-Карло'), ('analytical', 'Аналитический')], max_length=50)),
                ('diff_coefficient', models.FloatField(default=12.0)),
                ('ambipolar_diff_coefficient', models.FloatField(default=25.0)),
                ('trials_count', models.IntegerField(default=20)),
                ('particles_count', models.IntegerField(default=50000)),
                ('let_values_count', models.IntegerField(default=300)),
                ('simulation_result', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.DeleteModel(
            name='SimulationResult',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
