# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 17:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_auto_20180407_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='simulation_result',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
