# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_experiment_process_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_data',
            new_name='experimental_data',
        ),
    ]
