# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_auto_20180407_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='geometry',
            field=models.CharField(choices=[('disk', 'Диск'), ('sphere', 'Сфера')], default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='par1',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='par2',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='model_type',
            field=models.CharField(choices=[('point', 'Точечная модель'), ('voltage', 'Модель напряжений')], max_length=10),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sim_type',
            field=models.CharField(choices=[('monte_carlo', 'Монте-Карло'), ('analytical', 'Аналитический')], max_length=15),
        ),
    ]
