# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_auto_20180408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='par1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='par2',
            field=models.FloatField(null=True),
        ),
    ]
